# Execute your favorite apps at launch
exec-once = waybar
# exec-once = dunst
exec-once = sh -c 'pkill -x dunst 2>/dev/null; pkill -x mako 2>/dev/null; swaync'
exec-once = sh -c 'pkill -x hyprpaper 2>/dev/null; hyprpaper & sleep 1; walt random'


# Load configuration from ML4W Hyprland Settings App
exec = ~/.config/ml4w-hyprland-settings/hyprctl.sh
