# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = workspace 4 silent, match:class Spotify
windowrule = tile on, match:class Spotify

windowrule = workspace 4 silent, match:class org.telegram.desktop
windowrule = tile on, match:class org.telegram.desktop